{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Application ready time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "application_ready_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Main: Total vs Free disk bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "disk_free_bytes{job=\"Main-microservice\"}"
    },
    {
     "expr": "disk_total_bytes{job=\"Main-microservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Microservice: Free vs Used disk bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "disk_free_bytes{job=\"Trainer-workload-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "disk_total_bytes{job=\"Trainer-workload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active/Inactive users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "users_active_total", "legendFormat": "__auto" },
    { "expr": "users_inactive_total", "legendFormat": "__auto" }
   ]
  }
 ]
}